//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProtoClient.TemperatureConverterService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.unityconstruct.org/", ConfigurationName="TemperatureConverterService.TemperatureConverterSoap")]
    public interface TemperatureConverterSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.unityconstruct.org/ConvertFahernheitToCelsius", ReplyAction="*")]
        double ConvertFahernheitToCelsius(double Farhenheit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.unityconstruct.org/ConvertFahernheitToCelsius", ReplyAction="*")]
        System.Threading.Tasks.Task<double> ConvertFahernheitToCelsiusAsync(double Farhenheit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.unityconstruct.org/ConvertCelsiusToFahernheit", ReplyAction="*")]
        double ConvertCelsiusToFahernheit(double Celsius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.unityconstruct.org/ConvertCelsiusToFahernheit", ReplyAction="*")]
        System.Threading.Tasks.Task<double> ConvertCelsiusToFahernheitAsync(double Celsius);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TemperatureConverterSoapChannel : ProtoClient.TemperatureConverterService.TemperatureConverterSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TemperatureConverterSoapClient : System.ServiceModel.ClientBase<ProtoClient.TemperatureConverterService.TemperatureConverterSoap>, ProtoClient.TemperatureConverterService.TemperatureConverterSoap {
        
        public TemperatureConverterSoapClient() {
        }
        
        public TemperatureConverterSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TemperatureConverterSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TemperatureConverterSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TemperatureConverterSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double ConvertFahernheitToCelsius(double Farhenheit) {
            return base.Channel.ConvertFahernheitToCelsius(Farhenheit);
        }
        
        public System.Threading.Tasks.Task<double> ConvertFahernheitToCelsiusAsync(double Farhenheit) {
            return base.Channel.ConvertFahernheitToCelsiusAsync(Farhenheit);
        }
        
        public double ConvertCelsiusToFahernheit(double Celsius) {
            return base.Channel.ConvertCelsiusToFahernheit(Celsius);
        }
        
        public System.Threading.Tasks.Task<double> ConvertCelsiusToFahernheitAsync(double Celsius) {
            return base.Channel.ConvertCelsiusToFahernheitAsync(Celsius);
        }
    }
}
